
Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/nested_decorator_catch_up.py", line 20, in <module>
    foo()
  File "tests/exceptions/source/backtrace/nested_decorator_catch_up.py", line 12, in foo
    bar()
  File "tests/exceptions/source/backtrace/nested_decorator_catch_up.py", line 17, in bar
    1 / 0
ZeroDivisionError: division by zero

Traceback (most recent call last):
> File "tests/exceptions/source/backtrace/nested_decorator_catch_up.py", line 20, in <module>
    foo()
  File "tests/exceptions/source/backtrace/nested_decorator_catch_up.py", line 12, in foo
    bar()
  File "tests/exceptions/source/backtrace/nested_decorator_catch_up.py", line 17, in bar
    1 / 0
ZeroDivisionError: division by zero
