
Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/chaining_third.py", line 46, in <module>
    a_decorator()
  File "tests/exceptions/source/backtrace/chaining_third.py", line 10, in a_decorator
    b_decorator()
> File "tests/exceptions/source/backtrace/chaining_third.py", line 22, in b_decorator
    c_decorated()
  File "tests/exceptions/source/backtrace/chaining_third.py", line 39, in c_decorated
    1 / 0
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/chaining_third.py", line 47, in <module>
    a_context_manager()
  File "tests/exceptions/source/backtrace/chaining_third.py", line 14, in a_context_manager
    b_context_manager()
> File "tests/exceptions/source/backtrace/chaining_third.py", line 27, in b_context_manager
    c_not_decorated()
  File "tests/exceptions/source/backtrace/chaining_third.py", line 43, in c_not_decorated
    1 / 0
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/chaining_third.py", line 48, in <module>
    a_explicit()
  File "tests/exceptions/source/backtrace/chaining_third.py", line 18, in a_explicit
    b_explicit()
> File "tests/exceptions/source/backtrace/chaining_third.py", line 32, in b_explicit
    c_not_decorated()
  File "tests/exceptions/source/backtrace/chaining_third.py", line 43, in c_not_decorated
    1 / 0
ZeroDivisionError: division by zero
