
Traceback (most recent call last):
> File "tests/exceptions/source/backtrace/frame_values_forward.py", line 24, in <module>
    c(k)
  File "tests/exceptions/source/backtrace/frame_values_forward.py", line 21, in c
    b(n - 1)
  File "tests/exceptions/source/backtrace/frame_values_forward.py", line 16, in b
    a(n - 1)
  File "tests/exceptions/source/backtrace/frame_values_forward.py", line 12, in a
    1 / n
ZeroDivisionError: division by zero
