
Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/nested.py", line 17, in <module>
    a(0)
> File "tests/exceptions/source/backtrace/nested.py", line 14, in a
    nested(x)
  File "tests/exceptions/source/backtrace/nested.py", line 12, in nested
    1 / i
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/nested.py", line 28, in <module>
    b(0)
> File "tests/exceptions/source/backtrace/nested.py", line 25, in b
    nested(x)
  File "tests/exceptions/source/backtrace/nested.py", line 22, in nested
    1 / i
ZeroDivisionError: division by zero

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/nested.py", line 41, in <module>
    c(0)
> File "tests/exceptions/source/backtrace/nested.py", line 36, in c
    nested(x)
  File "tests/exceptions/source/backtrace/nested.py", line 33, in nested
    1 / i
ZeroDivisionError: division by zero
